# Generated by Django 4.0.5 on 2022-06-18 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='hey', max_length=255),
            preserve_default=False,
        ),
    ]
